import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { ATRIBUTOS_PADRAO, Colors } from '@/src/theme/colors';
import type { SpecResponse } from '@/src/types/spec';
import { Pill } from './radar-ui';

const labels: Record<string, string> = { motor: 'Motor', potencia_cv: 'Potência', torque_nm: 'Torque', transmissao: 'Transmissão', tracao: 'Tração', peso_kg: 'Peso', comprimento_mm: 'Comprimento', largura_mm: 'Largura', altura_mm: 'Altura', capacidade_carga_kg: 'Carga', preco_base_brl: 'Preço base', consumo_cidade: 'Consumo urbano', consumo_estrada: 'Consumo rodoviário' };
export function CoverageChart({ history }: { history: SpecResponse[] }) {
  const [mode, setMode] = useState('Disponíveis');
  const [selected, setSelected] = useState('potencia_cv');
  const counts = ATRIBUTOS_PADRAO.map(key => history.filter(item => { const field = item.atributos[key]; return field && field.valor !== null && (mode === 'Alta confiança' ? field.confianca === 'alta' : field.confianca !== 'nao_encontrado'); }).length);
  const value = counts[ATRIBUTOS_PADRAO.indexOf(selected)];
  return <View style={s.panel}><View style={s.heading}><Text accessibilityRole="header" style={s.title}>Por dentro dos dados</Text><Text style={s.count}>{history.length} fichas</Text></View><Text style={s.description}>Cobertura dos atributos no seu histórico</Text><View style={s.filters}>{['Disponíveis', 'Alta confiança'].map(label => <Pill key={label} label={label} selected={mode === label} onPress={() => setMode(label)} />)}</View><View style={s.bars}>{ATRIBUTOS_PADRAO.map((key, index) => <Pressable key={key} accessibilityRole="button" accessibilityLabel={`${labels[key]}: ${counts[index]} de ${history.length} fichas`} accessibilityState={{ selected: key === selected }} onPress={() => setSelected(key)} style={s.barTouch}><View style={[s.bar, { height: counts[index] ? 10 + (counts[index] / Math.max(history.length, 1)) * 65 : 3, backgroundColor: key === selected ? Colors.fordBlue : '#91C3DB' }]} /><View style={[s.dot, key === selected && { backgroundColor: Colors.fordBlue }]} /></Pressable>)}</View><View style={s.caption}><Text style={s.label}>{labels[selected]}</Text><Text selectable style={s.value}>{value} / {history.length} fichas</Text></View><Text style={s.note}>{history.length ? 'Toque nas barras para explorar cada atributo.' : 'Suas consultas vão preencher este gráfico. Comece pelo chat.'}</Text></View>;
}
const s = StyleSheet.create({ panel: { backgroundColor: '#F1F6FA', borderRadius: 28, padding: 20, gap: 12 }, heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }, title: { color: Colors.textPrimary, fontSize: 18, fontWeight: '600', flexShrink: 1 }, count: { fontSize: 11, color: Colors.textSecondary }, description: { fontSize: 12, color: Colors.textSecondary }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, bars: { flexDirection: 'row', alignItems: 'flex-end', height: 100, borderBottomWidth: 1, borderBottomColor: '#B6CAD8' }, barTouch: { flex: 1, height: 100, justifyContent: 'flex-end', alignItems: 'center', gap: 8, paddingHorizontal: 3 }, bar: { width: '100%', borderTopLeftRadius: 6, borderTopRightRadius: 6 }, dot: { width: 4, height: 4, borderRadius: 2, backgroundColor: '#C1D4E0', marginBottom: 5 }, caption: { flexDirection: 'row', justifyContent: 'space-between' }, label: { color: Colors.textPrimary, fontSize: 13 }, value: { color: Colors.fordBlue, fontSize: 13, fontWeight: '600', fontVariant: ['tabular-nums'] }, note: { color: Colors.textSecondary, fontSize: 11, lineHeight: 17 } });
