export const Colors = {
  fordBlue: '#003087',
  fordBlueLight: '#1a4db3',
  background: '#f5f5f5',
  surface: '#ffffff',
  textPrimary: '#1a1a1a',
  textSecondary: '#666666',
  border: '#e0e0e0',
  confidenceAlta: '#2e7d32',
  confidenceInferida: '#e65100',
  confidenceNaoEncontrado: '#9e9e9e',
  error: '#c62828',
  success: '#2e7d32',
  compareWinner: '#e8f5e9',
  compareLooser: '#ffffff',
};

export const ATRIBUTOS_PADRAO = [
  'motor',
  'potencia_cv',
  'torque_nm',
  'transmissao',
  'tracao',
  'peso_kg',
  'comprimento_mm',
  'largura_mm',
  'altura_mm',
  'capacidade_carga_kg',
  'preco_base_brl',
  'consumo_cidade',
  'consumo_estrada',
];
