export const Colors = {
  fordBlue: '#315D7B',
  fordBlueLight: '#6E9FBE',
  background: '#EDF3F8',
  surface: '#ffffff',
  textPrimary: '#182E40',
  textSecondary: '#5E7485',
  border: '#DCE7EF',
  confidenceAlta: '#2e7d32',
  confidenceInferida: '#e65100',
  confidenceNaoEncontrado: '#9e9e9e',
  error: '#c62828',
  success: '#2e7d32',
  compareWinner: '#e8f5e9',
  compareLooser: '#ffffff',
};

export const ATRIBUTOS_PADRAO = [
  'motor',
  'potencia_cv',
  'torque_nm',
  'transmissao',
  'tracao',
  'peso_kg',
  'comprimento_mm',
  'largura_mm',
  'altura_mm',
  'capacidade_carga_kg',
  'preco_base_brl',
  'consumo_cidade',
  'consumo_estrada',
];
